@startuml
class Helpers {
+ {static} ArrayList<ArrayList<Integer>> menuImages
+ {static} int SHAWARMA_KEY
+ {static} int FALAFEL_KEY
+ {static} int GRILL_KEY
+ {static} int DEALS_KEY
+ {static} int SIDES_KEY
+ {static} int DRINKS_KEY
+ {static} void insertUsersData(ArrayList<User>,CallBackUser)
}


interface Helpers$CallBackUser {
~ void onSuccess(ArrayList<User>)
~ void onFailure(String)
}

class HomeFragment {
- ArrayList<Item> shawarmaData
- RecyclerView shawarmaList
- ArrayList<Item> falafelData
- RecyclerView falafelList
- ArrayList<Item> grillData
- RecyclerView grillList
- ArrayList<Item> dealsData
- RecyclerView dealsList
- ArrayList<Item> sidesData
- RecyclerView sidesList
- ArrayList<Item> drinksData
- RecyclerView drinksList
- RecyclerCustomAdapterMenu RecyclerAdapter
+ <<Create>> HomeFragment()
+ void onCreate(Bundle)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
+ void createList(ArrayList<Item>,DatabaseReference,String,HomeScreen.CallBackItems)
- void shawarmaListListener()
- void falafelListListener()
- void grillListListener()
- void dealsListListener()
- void sidesListListener()
- void drinksListListener()
}


class MainActivity {
- ImageView logo
# void onCreate(Bundle)
}


class SignUp {
- TextView moveToLogin
- EditText username
- EditText password
- EditText phoneNumber
- EditText confirmedPassword
- Button signUp
- ArrayList<User> usersData
# void onCreate(Bundle)
+ boolean checkUserExistnace(ArrayList<User>,String,String)
+ boolean isValidPhone(String)
+ boolean checkUser(ArrayList<User>,User,String)
- void signUpListener()
- void setId()
}


class ChangePassword {
- EditText newPassword
- EditText confirmedNewPassword
- Button setBtn
- TextView moveToLogin
- TextView moveToSignUp
- ArrayList<User> usersData
# void onCreate(Bundle)
+ boolean checkPasswordExistnace(ArrayList<User>,String)
+ void updatePassword()
- void setId()
- void setBtnListener()
}


class EndScreen {
- TextView earnedPoints
- Button restartBtn
- Button shareBtn
- Button saveBtn
- EditText orderName
- Button verifyBtn
- ActivityResultLauncher<Intent> contactPickerLauncher
# void onCreate(Bundle)
+ boolean checkNameExistence(String,ArrayList<Order>)
# void initActivityLauncher()
}


class User {
- String username
- String password
- String phoneNumber
- int points
- ArrayList<Order> savedOrders
+ <<Create>> User()
+ <<Create>> User(String,String,int,String,ArrayList<Order>)
+ <<Create>> User(String,String,String,int)
+ <<Create>> User(String,String,String)
+ String getUsername()
+ void setUsername(String)
+ String getPassword()
+ void setPassword(String)
+ String getPhoneNumber()
+ void setPhoneNumber(String)
+ int getPoints()
+ void setPoints(int)
+ void addPoints(int)
+ void removePoints(int)
+ ArrayList<Order> getSavedOrders()
+ void addOrder(Order)
+ String toString()
}


class ForgotPassword {
- EditText phoneNumber
- EditText enterCode
- Button sendSms
- TextView moveToLogin
- TextView moveToSignUp
- ArrayList<User> usersData
# void onCreate(Bundle)
+ boolean phoneIsExist(String,ArrayList<User>)
+ String sendCodeToSms()
+ void checkCode()
+ void onRequestPermissionsResult(int,String[],int[])
- void sendSmsListener()
- void setId()
}


class PaymentScreen {
- SeekBar pointsSeekBar
- Button payBtn
- TextView maxValuePoints
- TextView redeemedPoints
- RecyclerView orderList
- RecyclerCustomAdapterOrder orderAdapter
+ {static} int newPrice
- Button closeBtn
- TextView itemDetails
# void onCreate(Bundle)
+ {static} void setUserInFireBase(User)
}


class EditItem {
- ImageView itemImage
- LinearLayout toppingsButtons
- ArrayList<String> toppings
- Switch moreMeatSwitch
- RadioGroup meatTypes
- TextView chooseMeatMessage
- Button addItemBtn
- Item curItem
# void onCreate(Bundle)
+ {static} void setToppingsData(ArrayList<String>,ToppingsCallBack)
+ {static} void findItemByName(Item,String,ItemCallBack)
}


interface EditItem$ToppingsCallBack {
~ void onSuccess(ArrayList<String>)
~ void onFailure(String)
}

interface EditItem$ItemCallBack {
~ void onSuccess(Item)
~ void onFailure(String)
}

class AddOrder {
- RecyclerView savedOrderList
- RecyclerCustomAdapterOrder adapter
- Button addToOrder
- TextView itemDetails
- Button closeBtn
# void onCreate(Bundle)
}


class RecyclerCustomAdapterMenu {
- ArrayList<Item> itemsData
- OnMenuClickListener listener
- ArrayList<ArrayList<Integer>> images
+ <<Create>> RecyclerCustomAdapterMenu(ArrayList<Item>)
+ <<Create>> RecyclerCustomAdapterMenu(ArrayList<Item>,OnMenuClickListener)
+ <<Create>> RecyclerCustomAdapterMenu(ArrayList<Item>,ArrayList<ArrayList<Integer>>)
+ <<Create>> RecyclerCustomAdapterMenu(ArrayList<Item>,ArrayList<ArrayList<Integer>>,OnMenuClickListener)
+ ViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(ViewHolder,int)
+ int getItemCount()
}


interface RecyclerCustomAdapterMenu$OnMenuClickListener {
~ void onItemClick(int)
}

class RecyclerCustomAdapterMenu$ViewHolder {
- ImageView itemImage
- TextView itemName
- TextView countOfPepole
- TextView price
- ImageView veganSign
+ <<Create>> ViewHolder(View)
}


class Order {
- ArrayList<Item> userItems
- ArrayList<Integer> orderImages
- String orderName
+ <<Create>> Order(ArrayList<Item>)
+ <<Create>> Order(ArrayList<Item>,ArrayList<Integer>)
+ <<Create>> Order()
+ ArrayList<Item> getUserItems()
+ Item getItem(int)
+ void addItem(Item)
+ int getSize()
+ ArrayList<Integer> getOrderImages()
+ void setOrderImages(ArrayList<Integer>)
+ String getOrderName()
+ void setOrderName(String)
+ void addImage(int)
+ int calcPrice()
+ void removeItem(int)
- String checkMeatType(int)
+ String toString()
}


class HomeScreen {
- TextView name
- TextView points
+ {static} Button payment
- ImageButton tiktok
- ImageButton instegram
- ImageButton facebook
- ArrayList<User> usersData
+ {static} User curUser
+ {static} Order order
- ViewPagerAdapter fragmentAdapter
- ViewPager2 viewPager
- TabLayout tabLayout
# void onCreate(Bundle)
# void onResume()
+ User findUserByPhone(String,ArrayList<User>)
- void setId()
- void setFragments()
}


interface HomeScreen$CallBackItems {
~ void onSuccess(ArrayList<Item>)
~ void onFailure(String)
}

class ViewPagerAdapter {
- ArrayList<Fragment> fragments
+ <<Create>> ViewPagerAdapter(FragmentActivity)
+ <<Create>> ViewPagerAdapter(Fragment)
+ <<Create>> ViewPagerAdapter(FragmentManager,Lifecycle)
+ Fragment createFragment(int)
+ int getItemCount()
+ void addFragment(Fragment)
}


class Item {
- String name
- ArrayList<String> toppings
- int countOfPepole
- int price
- boolean isVeggie
- boolean moreMeat
- boolean chicken
- boolean veal
- boolean hodu
- boolean mix
- String type
~ int vealPrice
~ int hoduPrice
~ int mixPrice
~ int moreMeatPrice
+ <<Create>> Item()
+ <<Create>> Item(String,ArrayList<String>,int,int,boolean,boolean,boolean,boolean,boolean,boolean,String)
+ String getName()
+ void setName(String)
+ String getTop(int)
+ ArrayList<String> getToppings()
+ void addTopping(String)
+ int getCountOfPepole()
+ void setCountOfPepole(int)
+ int getPrice()
+ void setPrice(int)
+ boolean isVeggie()
+ void setVeggie(boolean)
+ boolean isMoreMeat()
+ void setMoreMeat(boolean)
+ boolean isChicken()
+ void setChicken(boolean)
+ boolean isVeal()
+ void setVeal(boolean)
+ boolean isHodu()
+ void setHodu(boolean)
+ boolean isMix()
+ void setMix(boolean)
+ String getType()
+ void setType(String)
+ String toString()
}


class OrdersFragment {
- ListView savedOrdersList
- ArrayList<String> ordersName
- TextView emptyMessage
+ <<Create>> OrdersFragment()
+ void onCreate(Bundle)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
}


class PersonalizeFragment {
- Spinner countOfPepoleInOrder
- String[] options
- SeekBar pricePerPerson
- TextView chosenPrice
- ArrayList<Item> filteredItems
- ArrayList<Integer> filteredImages
- Button generateBtn
- CheckBox veganOption
- CheckBox sharingOption
- RecyclerView filteredList
- ArrayList<Item> menu
+ <<Create>> PersonalizeFragment()
+ void onCreate(Bundle)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onViewCreated(View,Bundle)
- void generateBtnListener()
+ void insertMenuData(ArrayList<Item>,HomeScreen.CallBackItems)
+ void filterData(ArrayList<Item>,ArrayList<Item>,ArrayList<Integer>,Boolean,Boolean,int,int)
+ int findImage(String,int)
}


class Login {
- TextView moveToSignUp
- TextView moveToForgotPassword
- Button login
- EditText phoneNumber
- EditText password
- ArrayList<User> usersData
# void onCreate(Bundle)
+ int checkExistnace(ArrayList<User>,String,String)
- void setId()
- void loginListener()
}


class RecyclerCustomAdapterOrder {
- ArrayList<Item> itemsData
- ArrayList<Integer> images
- OnOrderClickListener listener
+ <<Create>> RecyclerCustomAdapterOrder(ArrayList<Item>)
+ <<Create>> RecyclerCustomAdapterOrder(ArrayList<Item>,ArrayList<Integer>)
+ <<Create>> RecyclerCustomAdapterOrder(ArrayList<Item>,ArrayList<Integer>,OnOrderClickListener)
+ RecyclerCustomAdapterOrder.ViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(RecyclerCustomAdapterOrder.ViewHolder,int)
+ void remove(int)
+ int getItemCount()
}


interface RecyclerCustomAdapterOrder$OnOrderClickListener {
~ void onItemClick(int)
}

class RecyclerCustomAdapterOrder$ViewHolder {
- ImageView itemImage
- TextView itemName
- TextView countOfPepole
- TextView price
- ImageView veganSign
+ <<Create>> ViewHolder(View)
}




Helpers +.. Helpers$CallBackUser
Fragment <|-- HomeFragment
AppCompatActivity <|-- MainActivity
AppCompatActivity <|-- SignUp
AppCompatActivity <|-- ChangePassword
AppCompatActivity <|-- EndScreen
AppCompatActivity <|-- ForgotPassword
AppCompatActivity <|-- PaymentScreen
AppCompatActivity <|-- EditItem
EditItem +.. EditItem$ToppingsCallBack
EditItem +.. EditItem$ItemCallBack
AppCompatActivity <|-- AddOrder
Adapter <|-- RecyclerCustomAdapterMenu
RecyclerCustomAdapterMenu +.. RecyclerCustomAdapterMenu$OnMenuClickListener
RecyclerCustomAdapterMenu +.. RecyclerCustomAdapterMenu$ViewHolder
ViewHolder <|-- RecyclerCustomAdapterMenu$ViewHolder
AppCompatActivity <|-- HomeScreen
HomeScreen +.. HomeScreen$CallBackItems
FragmentStateAdapter <|-- ViewPagerAdapter
Fragment <|-- OrdersFragment
Fragment <|-- PersonalizeFragment
AppCompatActivity <|-- Login
Adapter <|-- RecyclerCustomAdapterOrder
RecyclerCustomAdapterOrder +.. RecyclerCustomAdapterOrder$OnOrderClickListener
RecyclerCustomAdapterOrder +.. RecyclerCustomAdapterOrder$ViewHolder
ViewHolder <|-- RecyclerCustomAdapterOrder$ViewHolder
@enduml